### ISSUE TITLE
Move make_multiproof/insert_leaf/rebuild to be a trait/impl on Node

### ISSUE THREAD

**Issue by axic** [gballet/multiproof-rs#22]

**Comment by s1na** [comment]
`make_multiproof` and `insert_leaf` make sense if the Node is root, I'm not sure about `rebuild` though.

Alternative: add a `Trie` struct which has `root: Node` and define `make_multiproof` and `insert_leaf` on that?

**Comment by gballet** [comment]
Redundant with #8 #9 #10, closing

**Comment by axic** [comment]
@s1na why wouldn't rebuild make sense?

`Node::rebuild_from_multiproof(&multiproof) -> Node`, just like the `::new` function.

**Comment by s1na** [comment]
@axic that'll work, you're right
